"""fix_table

Revision ID: 230add5560a1
Revises: 
Create Date: 2022-12-02 18:51:18.217646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230add5560a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_dimension',
    sa.Column('concept_num', sa.String(length=255), nullable=False),
    sa.Column('name_char', sa.String(length=255), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('sourcesystem_cd', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('concept_num')
    )
    op.create_table('location',
    sa.Column('location_cd', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_cd')
    )
    op.create_table('patient_dimension',
    sa.Column('patient_num', sa.String(length=255), nullable=False),
    sa.Column('vital_status', sa.String(length=3), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('sex_cd', sa.String(length=1), nullable=True),
    sa.Column('age_in_years', sa.Integer(), nullable=True),
    sa.Column('race_cd', sa.String(length=1), nullable=True),
    sa.Column('marital_status_cd', sa.String(length=1), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('patient_num')
    )
    op.create_table('provider_dimension',
    sa.Column('provider_num', sa.String(length=255), nullable=False),
    sa.Column('name_char', sa.String(length=255), nullable=True),
    sa.Column('provider_blob', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('provider_num')
    )
    op.create_table('concept_descriptions',
    sa.Column('concept_num', sa.String(length=255), nullable=False),
    sa.Column('concept_term', sa.String(length=255), nullable=False),
    sa.Column('term_type', sa.String(length=255), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('sourcesystem_cd', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['concept_num'], ['concept_dimension.concept_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_num', 'concept_term')
    )
    op.create_table('concept_relationships',
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('type_cd', sa.String(length=255), nullable=False),
    sa.Column('import_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('sourcesystem_cd', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['concept_dimension.concept_num'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target'], ['concept_dimension.concept_num'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_cd'], ['concept_dimension.concept_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source', 'target', 'type_cd')
    )
    op.create_table('encounter_dimension',
    sa.Column('encounter_num', sa.String(length=255), nullable=False),
    sa.Column('location_cd', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('patient_num', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_cd'], ['location.location_cd'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_num'], ['patient_dimension.patient_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('encounter_num')
    )
    op.create_table('observation_fact',
    sa.Column('observation_id', sa.String(length=255), nullable=False),
    sa.Column('patient_num', sa.String(length=255), nullable=True),
    sa.Column('provider_num', sa.String(length=255), nullable=True),
    sa.Column('encounter_num', sa.String(length=255), nullable=True),
    sa.Column('concept_cd', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('valtype_cd', sa.String(length=3), nullable=True),
    sa.Column('tval_char', sa.String(length=255), nullable=True),
    sa.Column('nval_num', sa.Numeric(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_cd'], ['concept_dimension.concept_num'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_num'], ['encounter_dimension.encounter_num'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_num'], ['patient_dimension.patient_num'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_num'], ['provider_dimension.provider_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_fact')
    op.drop_table('encounter_dimension')
    op.drop_table('concept_relationships')
    op.drop_table('concept_descriptions')
    op.drop_table('provider_dimension')
    op.drop_table('patient_dimension')
    op.drop_table('location')
    op.drop_table('concept_dimension')
    # ### end Alembic commands ###
