"""add_unit

Revision ID: d15e1d7e03f7
Revises: 230add5560a1
Create Date: 2022-12-02 23:49:08.344835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15e1d7e03f7'
down_revision = '230add5560a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation_fact', sa.Column('unit', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observation_fact', 'unit')
    # ### end Alembic commands ###
